wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1683405452.449338
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 33
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 33
      - 53
      - 55
      3:
      - 23
      4: 3.10.11
      5: 0.15.2
      8:
      - 1
      - 5
      - 12
alpha:
  desc: null
  value: 0.9700662822607893
eta:
  desc: null
  value: 0.6438566750092768
num_topics:
  desc: null
  value: 9
passes:
  desc: null
  value: 9
