wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.0
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1682977072.057348
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.11
      5: 0.15.0
      8:
      - 1
      - 5
alpha:
  desc: null
  value: 0.6704362571518339
eta:
  desc: null
  value: 0.8167598542459518
num_topics:
  desc: null
  value: 10
passes:
  desc: null
  value: 9
